"""Safe filesystem paths for generated, prepared, and published images.

User-supplied paths are never used. Internal names are generated by the service.
"""

from __future__ import annotations

import re
from pathlib import Path
from uuid import uuid4

from models.errors import AppError, ErrorCode

STORAGE_STAGES = frozenset({"generated", "prepared", "published"})
SAFE_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$")
INTERNAL_FILENAME_RE = re.compile(r"^img_[0-9a-f]{32}\.(png|jpg|jpeg)$", re.IGNORECASE)
ALLOWED_EXTENSIONS = frozenset({"png", "jpg", "jpeg"})


def _reject_path(message: str = "Invalid storage path.") -> None:
    raise AppError(ErrorCode.INVALID_REQUEST, message, http_status=400)


UNSAFE_USER_CHARS = re.compile(r"[^A-Za-z0-9_-]")


def assert_safe_token(value: str, *, label: str) -> str:
    token = (value or "").strip()
    if not token or not SAFE_ID_RE.fullmatch(token) or ".." in token:
        _reject_path(f"Invalid {label}.")
    if Path(token).name != token:
        _reject_path(f"Invalid {label}.")
    return token


def assert_safe_user_id(user_id: str) -> str:
    cleaned = UNSAFE_USER_CHARS.sub("", (user_id or "").strip())[:64] or "unknown"
    if not SAFE_ID_RE.fullmatch(cleaned) or ".." in cleaned:
        _reject_path("Invalid user id.")
    return cleaned


def assert_safe_image_id(image_id: str) -> str:
    return assert_safe_token(image_id, label="image id")


def assert_internal_filename(filename: str) -> str:
    name = (filename or "").strip()
    if Path(name).name != name or ".." in name or not INTERNAL_FILENAME_RE.fullmatch(name):
        _reject_path("Invalid media filename.")
    return name.lower() if name.endswith((".PNG", ".JPG", ".JPEG")) else name


def generate_internal_filename(extension: str) -> str:
    ext = (extension or "").lower().lstrip(".")
    if ext == "jpeg":
        ext = "jpg"
    if ext not in {"png", "jpg"}:
        raise AppError(
            ErrorCode.UNSUPPORTED_FORMAT,
            "Only JPEG and PNG images are supported.",
            http_status=400,
        )
    return f"img_{uuid4().hex}.{ext}"


def is_within(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
        return True
    except ValueError:
        return False


def resolve_contained(root: Path, *parts: str) -> Path:
    root_resolved = Path(root).resolve()
    for part in parts:
        if not part or part in {".", ".."} or "/" in part or "\\" in part or ".." in part:
            _reject_path()
        if Path(part).name != part:
            _reject_path()
    candidate = root_resolved.joinpath(*parts).resolve()
    if not is_within(candidate, root_resolved):
        _reject_path()
    return candidate


def atomic_write(path: Path, data: bytes) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_name(path.name + ".tmp")
    try:
        tmp_path.write_bytes(data)
        tmp_path.replace(path)
    except OSError as exc:
        tmp_path.unlink(missing_ok=True)
        raise AppError(
            ErrorCode.STORAGE_FAILURE,
            "The image could not be stored.",
            http_status=500,
        ) from exc
    return path


class MediaPaths:
    def __init__(self, media_root: Path) -> None:
        self.root = Path(media_root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def stage_root(self, stage: str) -> Path:
        if stage not in STORAGE_STAGES:
            _reject_path("Invalid media stage.")
        return resolve_contained(self.root, stage)

    def user_dir(self, stage: str, user_id: str) -> Path:
        if stage not in STORAGE_STAGES:
            _reject_path("Invalid media stage.")
        return resolve_contained(self.root, stage, assert_safe_user_id(user_id))

    def image_file(self, stage: str, user_id: str, filename: str) -> Path:
        if stage not in STORAGE_STAGES:
            _reject_path("Invalid media stage.")
        return resolve_contained(
            self.root,
            stage,
            assert_safe_user_id(user_id),
            assert_internal_filename(filename),
        )

    def relative_to_root(self, path: Path) -> str:
        resolved = Path(path).resolve()
        if not is_within(resolved, self.root):
            _reject_path()
        return resolved.relative_to(self.root).as_posix()

    def from_relative(self, relpath: str) -> Path:
        if not relpath or relpath.startswith("/") or relpath.startswith("\\"):
            _reject_path()
        parts = Path(relpath.replace("\\", "/")).parts
        if ".." in parts or not parts:
            _reject_path()
        return resolve_contained(self.root, *parts)

    def assert_contained(self, path: Path) -> Path:
        resolved = Path(path).resolve()
        if not resolved.is_file() or not is_within(resolved, self.root):
            raise AppError(ErrorCode.TASK_NOT_FOUND, "Media file was not found.", http_status=404)
        return resolved
