"""SQLAlchemy persistence for the Instagram Agentic AI platform.

Public interface for Agent 3 and later agents. Route handlers must use repositories,
not raw Session queries.
"""

from db.base import Base, new_id, utcnow
from db.crypto import TokenEncryptor, decrypt_token, encrypt_token
from db.enums import (
    DEFAULT_TIMEZONE,
    NON_PUBLISHED_POST_STATUSES,
    AccountStatus,
    ApprovalStatus,
    FestivalPostStatus,
    GenerationStatus,
    ImageSource,
    JobStatus,
    JobType,
    PostStatus,
    PostType,
    TaskTrigger,
    TaskType,
)
from db.exceptions import DuplicateRecordError, PersistenceError, RecordNotFoundError, TokenEncryptionError
from db.asset_repositories import (
    BrandGuidelineRepository,
    BrandProfileRepository,
    BusinessAssetRepository,
    ProductAssetRepository,
    ProductRepository,
)
from db.models import (
    AgentEvent,
    AgentTask,
    AutomationSettings,
    BrandGuideline,
    BrandProfile,
    BusinessAsset,
    BusinessProfile,
    FestivalCampaign,
    FestivalPost,
    GeneratedImage,
    InstagramAccount,
    InstagramPost,
    Product,
    ProductAsset,
    ScheduledJob,
    User,
)
from db.persist import load_agent_state, persist_agent_state
from db.repositories import (
    AgentEventRepository,
    AgentTaskRepository,
    AutomationSettingsRepository,
    BusinessProfileRepository,
    FestivalCampaignRepository,
    FestivalPostRepository,
    GeneratedImageRepository,
    InstagramAccountRepository,
    InstagramPostRepository,
    ScheduledJobRepository,
    UserRepository,
    SessionRepository,
    BusinessRepository,
    AutomationRepository,
    PostRepository,
    TaskRepository,
    FestivalRepository,
    JobRepository,
    DailySlotRepository,
)
from db.session import (
    bootstrap_database,
    create_engine_from_settings,
    create_engine_from_url,
    get_db,
    init_db,
    session_factory,
)
from db.uow import Database, get_database

__all__ = [
    "AccountStatus",
    "AgentEvent",
    "AgentEventRepository",
    "AgentTask",
    "AgentTaskRepository",
    "ApprovalStatus",
    "AutomationSettings",
    "AutomationSettingsRepository",
    "Base",
    "BrandGuideline",
    "BrandGuidelineRepository",
    "BrandProfile",
    "BrandProfileRepository",
    "BusinessAsset",
    "BusinessAssetRepository",
    "BusinessProfile",
    "BusinessProfileRepository",
    "DEFAULT_TIMEZONE",
    "Database",
    "DuplicateRecordError",
    "FestivalCampaign",
    "FestivalCampaignRepository",
    "FestivalPost",
    "FestivalPostRepository",
    "FestivalPostStatus",
    "GeneratedImage",
    "GeneratedImageRepository",
    "GenerationStatus",
    "ImageSource",
    "InstagramAccount",
    "InstagramAccountRepository",
    "InstagramPost",
    "InstagramPostRepository",
    "JobStatus",
    "JobType",
    "NON_PUBLISHED_POST_STATUSES",
    "PersistenceError",
    "PostStatus",
    "PostType",
    "Product",
    "ProductAsset",
    "ProductAssetRepository",
    "ProductRepository",
    "RecordNotFoundError",
    "ScheduledJob",
    "ScheduledJobRepository",
    "TaskTrigger",
    "TaskType",
    "TokenEncryptionError",
    "TokenEncryptor",
    "User",
    "UserRepository",
    "SessionRepository",
    "BusinessRepository",
    "AutomationRepository",
    "PostRepository",
    "TaskRepository",
    "FestivalRepository",
    "JobRepository",
    "DailySlotRepository",
    "bootstrap_database",
    "create_engine_from_settings",
    "create_engine_from_url",
    "decrypt_token",
    "encrypt_token",
    "get_database",
    "get_db",
    "init_db",
    "load_agent_state",
    "new_id",
    "persist_agent_state",
    "session_factory",
    "utcnow",
]
